### ISSUE TITLE
Add getUserMedia permissions

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/permissions#10]
I think getUserMedia has a minimum of two permissions ```capture-audio``` and ```capture-video```. But we could try to merge them into one like:
```js { "name": "capture", "audio": true, "video": true }```

I'm not convinced that having the object would be better but I think we should get some feedback from the spec editors. IIRC, @marcoscaceres, we tried to do that and it didn't work. Do you remember what hoppened?

**Comment by alvestrand** [comment]
getUserMedia has either one (access devices), two (audio and video) or one permission per device. Implememtations vary in how they model this.

suggest to take this question to the public-media-capture list.

**Comment by jimmywarting** [comment]
:+1:

**Comment by alvestrand** [comment]
I think that this can be closed given #57 and #68.

**Comment by mounirlamouri** [comment]
Correct :)
