### ISSUE TITLE
Move the Permissions registry

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/permissions#103]
The Permissions Registry being in the middle of the spec is quite distracting. It adds a lot of unnecessary noise right in the middle of the spec, before the interfaces have been introduced, etc.... making the spec more difficult to follow than it should be.

Can I suggest that we move it to the end of the document or remove the registry entirely? IMHO, each registry item should be moved (normatively) to their respective specs. We could then link to those specs, non-normatively, but the registry doesn't really belong in this spec.

**Comment by jyasskin** [comment]
Yes, we should move it. For WebIDL reasons, I think we need to keep the enum all in one place (https://www.w3.org/Bugs/Public/show_bug.cgi?id=27048), but maybe that should be the [Feature Policy](https://wicg.github.io/feature-policy/) spec. It's totally reasonable to have the individual enum values link off to other specs, like `"bluetooth"` already does. For specs that aren't in active development, the end of the Permissions document seems ok.

**Comment by marcoscaceres** [comment]
> For specs that aren't in active development, the end of the Permissions document seems ok.

Agree. Though we should probably reactive any of those - as no spec used by browsers should be frozen*.

<small>* terms and conditions apply</small>
