### ISSUE TITLE
Should Permissions be an interface with static objects?

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/permissions#11]
The WIP TAG review points that the Permissions class should be instanciated on the navigator object. It seems that everyone has different opinions on the matter.

The main argument of the TAG review is that Permissions holds a collection of permissions which is not in the spirit of the specification.

The current design is meant to reduce API footprint and make it look and behave more like a module.

CC @annevk @domenic @slightlyoff @marcoscaceres @jakearchibald

**Comment by annevk** [comment]
Without modules the precedent set by the URL and CSS globals seems fine to follow. I could also see `navigator.permissions` I suppose. It doesn't really matter much as long as there are no modules.
