### ISSUE TITLE
Guidance on where to put permission related stuff in other specs

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/permissions#110]
We should probably provide better guidance as to where to put permission related stuff in specs. 

For instance, [Magnetometer](https://w3c.github.io/magnetometer/) puts the permission info into its "Model" section. I don't think that's ideal, as it makes it hard to find... 

Has any "best practice" emerged yet? We should suggest something to spec authors.

**Comment by annevk** [comment]
I would particularly be interested in advice as to how to hook into Permissions. I need to do this for the Notifications API and Storage. At the moment I use language like

* If permission for notification’s origin is not "granted"...
* The static permission attribute’s getter must return permission for the entry settings object’s origin.
* Set permission for the entry settings object’s origin to permission.

and I'd love to rephrase that in a way that hooks into Permissions directly. See https://github.com/whatwg/notifications/issues/71 for the issue I have on doing that. Perhaps you or @jyasskin is interested in doing that work? It should be fairly easy I think once you're familiar with the setup (which I'm not).

**Comment by jyasskin** [comment]
I've now updated Web Bluetooth to use the new permission structure. Look at uses of "permission state" and "extra permission data" in https://webbluetoothcg.github.io/web-bluetooth/, and at the definition of the [`"bluetooth"` powerful feature](https://webbluetoothcg.github.io/web-bluetooth/#dom-permissionname-bluetooth).

I think we should try out the integration in a couple other specs before baking a best practice into this one, but once we have a few examples I can add some guidance to this spec.

**Comment by jyasskin** [comment]
Here's a change for Storage: https://github.com/whatwg/storage/pull/36

**Comment by marcoscaceres** [comment]
We export various algorithms now... so closing.
