### ISSUE TITLE
Flesh out request("push")

### ISSUE THREAD

**Issue by jyasskin** [w3c/permissions#111]
1. [`serviceWorkerRegistration.pushManager.subscribe()`](https://w3c.github.io/push-api/#widl-PushManager-subscribe-Promise-PushSubscription--PushSubscriptionOptionsInit-options) needs a `ServiceWorkerRegistration`. Should that be a required member of [`PushPermissionDescriptor`](https://w3c.github.io/permissions/#dictdef-pushpermissiondescriptor) or what?
2. [`subscribe()`](https://w3c.github.io/push-api/#widl-PushManager-subscribe-Promise-PushSubscription--PushSubscriptionOptionsInit-options) fails in at least 4 ways. We need to figure out which of these reject the `request()` promise, and which are communicated in other ways. Having the permission be denied is not exceptional for permissions.request(), so at least NotAllowedError needs to be a fulfillment with a particular state.
   1. SecurityError
   2. InvalidAccessError
   3. InvalidStateError
   4. NotAllowedError
   5. AbortError

@mounirlamouri @mvano @martinthomson (Martin, this doesn't presuppose the answer to #83, but the complexity of specifying request() could affect the decision there.)

**Comment by martinthomson** [comment]
Permissions probably can't be scoped to a specific service worker, unless you have some idea how you might talk to a user about this concept.

I don't know how you change the API to avoid rejections without creating a whole lot of bustage.

**Comment by marcoscaceres** [comment]
Closing as per  #83.
