### ISSUE TITLE
Flesh out request("geolocation")

### ISSUE THREAD

**Issue by jyasskin** [w3c/permissions#112]
[`"geolocation"`](https://w3c.github.io/permissions/#geolocation) is currently specified as a boolean feature, but `request()` needs to work on browsers like Firefox that let the user grant one location stream but still prompt for the next request in the same realm. That is, request()'s result needs to include a location or a location stream, which means the input needs to include the [`PositionOptions`](https://dev.w3.org/geo/api/spec-source.html#position_options_interface).

I assume we don't want to open up a position stream unless the caller wants it, since watching a location costs more and shows the location indicator for longer than getting a single point. But the stream should be possible, and more idiomatic than `watchPosition()`, so we need to design that.

We also need to figure out what to do with [`POSITION_UNAVAILABLE`](https://dev.w3.org/geo/api/spec-source.html#position_unavailable_error) and [`TIMEOUT`](https://dev.w3.org/geo/api/spec-source.html#timeout_error). Are they rejected promises or some field in the result?

**Comment by marcoscaceres** [comment]
> "geolocation" is currently specified as a boolean feature, but request() needs to work on browsers like Firefox that let the user grant one location stream but still prompt for the next request in the same realm. That is, request()'s result needs to include a location or a location stream, which means the input needs to include the PositionOptions.

I think we could change Firefox's behavior that if a .request() is made, then you just grant it without needing to ask for it again in the same realm, and for a given origin. 

> I assume we don't want to open up a position stream unless the caller wants it, since watching a location costs more and shows the location indicator for longer than getting a single point. 

Correct, granting permission should not have side effects (i.e., it should not spin up the geolocation, it just says that you are allowed to use the API for this origin - and for this session). 

> We also need to figure out what to do with POSITION_UNAVAILABLE and TIMEOUT. Are they rejected promises or some field in the result?

If we decouple request() from activation of geolocation, we don't need to do anything. 

Then POSITION_UNAVAILABLE and TIMEOUT continue to be handled by watchPosition() and getCurrentPosition().

**Comment by martinthomson** [comment]
> I think we could change Firefox's behavior that if a .request() is made, then you just grant it without needing to ask for it again in the same realm, and for a given origin. 

That's tricky, and I doubt that you'd find this easy.  It all depends on what you believe the model to be.  The prevailing view is that without the "don't ask me again" checkbox enabled, this is a one-off grant for where I currently am.

However, if your assertion is that `watchPosition` allows for a stream of requests that are not further gated on a prompt, that's a fair call.  I don't know exactly what the expected outcome is here.

**Comment by marcoscaceres** [comment]
> On 8 Aug 2016, at 9:12 PM, Martin Thomson <notifications@github.com> wrote:
> 
> I think we could change Firefox's behavior that if a .request() is made, then you just grant it without needing to ask for it again in the same realm, and for a given origin.
> 
> That's tricky, and I doubt that you'd find this easy.
> 

Maybe. Need to poke around the security manager in Gecko.

> It all depends on what you believe the model to be. The prevailing view is that without the "don't ask me again" checkbox enabled, this is a one-off grant for where I currently am.
> 

Yeah, it's a tricky one because, for instance, iOS only supports "always" and no checkbox. In any case, we need to support session based and persistent permissions... But making these based on realms instead of origins seems overly complicated. 

> However, if your assertion is that watchPosition allows for a stream of requests that are not further gated on a prompt, that's a fair call. I don't know exactly what the expected outcome is here.
> 

Well, we should get agreement on the semantics of "request()" wrt its effect on subsequent calls to the APIs it relates to. The OP seems to imply side effects, because it seems to conflate a relationship to geolocation's error callbacks?

**Comment by RichardMaher** [comment]
@jyasskin I agree that a boolean does not meet the requirements of the Location permission query or request.

Granularity must be extended to cover and distinguish "Background Location Tracking" from "Foreground Location tracking". Whether "At sleep Location tracking" granularity is also required is doubtful as I believe it can be combined with "Background" perhaps under a better name.

"Covert" seems emotive. How about Unwatched? Unsupervised? Neglected? Continuous? Resilient? Ambient?

**Comment by marcoscaceres** [comment]
> Granularity must be extended to cover and distinguish "Background Location Tracking" from "Foreground Location tracking". Whether "At sleep Location tracking" granularity is also required is doubtful as I believe it can be combined with "Background" perhaps under a better name.

It's too early to be talking about this. AFAIK, no one is actually planning on implementing background geolocation at this point (or did I miss the memo?).

**Comment by RichardMaher** [comment]
I was not aware that an implementation was a prerequisite for a specification. Nevertheless, Firebase are currently working on implementing Background Geolocation in their library: -
 [4-9024000017061] WebApp Background Geolocation via Firebase

Their track-record in providing much needed cross-browser functionality over and above what can be found in the specification is well-known. Topic-Based subscription for Push Messages a stunning case in point.

I just hope they are able to bring the same outside-the-square thinking to Background Geolocation. I also hope the divide between the PWA and the Ultimate Usurper Web App camps does not develop into a full blown schism.

**Comment by marcoscaceres** [comment]
> I was not aware that an implementation was a prerequisite for a specification. 

it is. W3C "standardizes" things (i.e., it harmonizes implementation through consensus, whose output is usually a specification with intellectual property protections for those involved). 
 
> Nevertheless, Firebase are currently working on implementing Background Geolocation in their library.

If they can solve it with a library, we might not need to do any browser work. 

I'm wondering if you've had a chance to read the [Extensible Web Manifesto](https://extensiblewebmanifesto.org)?. If Firebase manages to solve it by using existing primitives in the platform, we might not need to do anything here.

**Comment by RichardMaher** [comment]
FYI iOS has a couple of different approaches: -
1) locationManager.requestAlwaysAuthorization() and locationManager.requestWhenInUseAuthorization() these are mutually exclusive. Interesting thing about AlwaysAuthorization is that apparently it reprompts after every few days for confirmation.
2) Background App Refresh. Very course granularity but another option all the same. What have you spec'd for Background Synch and/or Background Fetch?

**Comment by marcoscaceres** [comment]
Thanks for the additional pointers. I can't recall what we do for background sync and fetch.

**Comment by RichardMaher** [comment]
Looks like Google Chrome has set the precedent for an opt-out strategy for background processing: -
https://wicg.github.io/BackgroundSync/spec/#privacy-considerations

I surprised your Manager didn't ask "How did that get into the spec?"

or "Won't my battery run down fast with all these retries?" or "They tracked my IP!"

Anyway, the good news for Background GeoLocation is this Opt-Out strategy sits well with Androids API requiring an explicit stop.

**Comment by RichardMaher** [comment]
Can't wait to see someone explain the bandwidth loss to end-users when that haven't realized that they needed to opt-out of Background Fetch. Still you can't have too many movies in memory I suppose.

**Comment by jakearchibald** [comment]
@RichardMaher I think you've misunderstood what background sync can do in terms of background processing. You're also using background sync & background fetch interchangeably when they're different things.

Consider for a moment that you're not the only non-idiot in the world, and others are working hard to do the right thing, and the issue *could possibly be* your own understanding.

With that in mind, can you explain the issues you see with background sync & fetch?

**Comment by jan-ivar** [comment]
This issue seems moot since `request` is out https://github.com/w3c/permissions/issues/83#issuecomment-246564060.

**Comment by RichardMaher** [comment]
Hi @jan-ivar Your interaction there was both compelling and succinct so if you can please address these issues I have with the Capability Model I would really appreciate it: -

1) Do you accept that there are/will be capabilities that can only be tested in a Service Worker when, potentially,  no UI is available? If so, and I hope you accept that's a given, how can the user be prompted for permission?
2) Do you agree that the advent of Web-Apps becoming first-class citizens on their host OS compels us to revisit Manifest declaration of permission requirements to be displayed in the App Drawer?
3) Do you accept that there are/will be features that require an ANDing of permissions to operate correctly or not at all. Does it not make sense to ask for all at the same time? A new super-permission?

Cheers

**Comment by marcoscaceres** [comment]
Closing as invalid, as .request() is no longer a thing here.
