### ISSUE TITLE
deploy.sh doesn't fail for patches with bikeshed errors

### ISSUE THREAD

**Issue by jyasskin** [w3c/permissions#123]
#120 introduced a link error (`LINK ERROR: No 'idl' refs found for 'PermissionDesc'.`), but the Travis build didn't warn us. We'll have to use an extra request with `-F output=err` to catch errors, like https://github.com/WebBluetoothCG/web-bluetooth/blob/master/deploy.sh uses.

**Comment by marcoscaceres** [comment]
closing. Handled by #241
