### ISSUE TITLE
Incorrectly says "camera", "microphone" aren't allowed in non-secure contexts.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/permissions#128]
https://w3c.github.io/permissions/#media-devices says:

*"The "camera", "microphone" , and "speaker" permissions are associated with permission to use media devices as specified in [GETUSERMEDIA] and [audio-output]. "speaker" is [allowed in non-secure contexts](https://w3c.github.io/permissions/#allowed-in-non-secure-contexts)."*

Unless I'm misunderstanding what a "flag" is, this says that all browsers must disallow "camera" and "microphone" in non-secure origins, which does not match what the mediacapture spec [says](https://w3c.github.io/mediacapture-main/getusermedia.html#local-content):

 *"When on an insecure origin [[mixed-content](https://w3c.github.io/mediacapture-main/getusermedia.html#bib-mixed-content)], User Agents are encouraged to warn about usage of `navigator.mediaDevices.getUserMedia`, `navigator.getUserMedia` ... It is explicitly permitted for User Agents to remove these APIs entirely when on an insecure origin, ..."*

The permission spec should be updated to correctly reflect the mediacapture spec: that browsers may or may not support `getUserMedia` in http.

**Comment by jyasskin** [comment]
This is why I want to move all the permission algorithms into the specs that define the features. ;) Want to send a PR to set the flag for the "camera" and "microphone" too?
