### ISSUE TITLE
Support for custom permission types

### ISSUE THREAD

**Issue by ThomasArdal** [w3c/permissions#130]
Handling permissions in the browser is a great idea. But why limit the permission to an enum? Supporting permissions, would allow for a website to ask for permission (through the browser), for something that makes sense for that domain. Could be "ask for permission to store my data", "ask for permission to sync with my calendar" etc. Having a standard for asking for permissions and storing the results, would make it easier for website developers to implement features like this across browsers.

**Comment by jyasskin** [comment]
That goes toward a "Permission Provider" API, where site A would offer a type of permission, and then sites B, C, and D could ask the user for permission to access site A's data. I think it's worth doing, but we haven't seen (or, really, looked for) much interest from major sites that would be defining those permissions. It's also a significant expansion in the scope of this API and should probably go through the [WICG](https://wicg.io/) before landing here.

Does that make sense?

**Comment by jyasskin** [comment]
I should add that the TAG agrees with you: https://github.com/w3ctag/spec-reviews/blob/master/2015/03/Permissions.md#issue-extensibility-persistence-subclassing-and-constructors.

**Comment by ThomasArdal** [comment]
Makes sense. I hadn't thought about the possibility to share a permission between site A, B, C and D. But now that you mention it, that would make sense as well, and comply pretty well with the existing permission types (geo, notification etc.).

**Comment by jyasskin** [comment]
The reason to have sites share a permission name is that if a site "ask[s] for permission to sync with my calendar", and I say 'yes', that should actually grant it permission to sync with my calendar. If the site itself stored my calendar, then it wouldn't really need permission, and if it doesn't store my calendar, then it needs my 'yes' to be conveyed in a trusted way to the site that does store the calendar.

**Comment by benfredwells** [comment]
Using permissions to allow sites to interop is really interesting. If anything happens please stay in sync with the [Ballista project](https://github.com/chromium/ballista), which is solving similar issues (and has spun out the web-share and web-share-target proposals)

**Comment by ThomasArdal** [comment]
@benfredwells Looks cool

@jyasskin Maybe this issue should be closed?

**Comment by marcoscaceres** [comment]
Although an interesting proposal, I'm going to close this as out of scope - and I think a lot these are best handled by particular APIs (e.g., web share+target, registerProtocolHandler(), etc). I'd also be concerned about random permissions being conflated with permissions that enable powerful features.
