### ISSUE TITLE
Drop "The" from title

### ISSUE THREAD

**Issue by annevk** [w3c/permissions#132]
Seems a little nicer to be able to refer to this as the Permissions API rather than The Permissions API. See also Fullscreen API and Notifications API.

**Comment by jyasskin** [comment]
https://w3c.github.io/permissions/ is titled just "Permissions" because it covers more than just the API. We still haven't gotten Echidna working, to auto-publish that to https://www.w3.org/TR/permissions/.

**Comment by annevk** [comment]
Ah okay. Sorry for the noise.
