### ISSUE TITLE
Mechanism for permission feature-detection?

### ISSUE THREAD

**Issue by RByers** [w3c/permissions#134]
Is it possible that an application may want to have different behavior depending on whether a permission is supported by the browser or not?  Should there perhaps be some mechanism for feature-detecting unsupported permissions separately from denied permissions?

I'm just worried about developers relying on UserAgent checks (which then cause interoperability and forwards compatibility issues) when what they really want is a permission feature detect.

/cc @jyasskin where this came up in [the intent-to-ship for web bluetooth](https://groups.google.com/a/chromium.org/d/msg/blink-dev/Ono3RWkejAA/37k_TWevAgAJ).

**Comment by jyasskin** [comment]
`permissions.query({name: "Unknown"})` rejects with a `TypeError`, while `permissions.query({name: "Denied"})` fulfils with a [`PermissionStatus`](https://w3c.github.io/permissions/#permissionstatus) containing `{state: "denied"}`.

It might make sense to add a more explicit operation to check whether a permission is supported, but they're at least distinguishable now.

**Comment by RByers** [comment]
Oh sorry, I misunderstood your point in the i2s then (so those cases you mentioned ARE feature-detectable).  That seems good enough to me - feel free to close if there's no evidence that you need something more explicit.

**Comment by marcoscaceres** [comment]
I think this is now handled by permission policy's API... a document (or iframe) can check which features it has access to independently of what a permission state is.
