### ISSUE TITLE
May reorder the permission state read steps

### ISSUE THREAD

**Issue by zakorgy** [w3c/permissions#137]
Sorry if there was an issue in this topic, but I didn't found any. As I see Step 2 and 3 in https://w3c.github.io/permissions/#permission-state could be switched. Both depends on the same `setting` and `descriptor`, and moving the current Step 3 forward results in non-secure contexts an early return, if there was a previous invocation of this algorithm (the result of this invocation is also stored), and there is no new information about the user’s intent. Correct me if I'm wrong.

**Comment by jyasskin** [comment]
I think it's true that they could be switched, but it makes it a little less clear that non-secure contexts could be pinned to `"denied"`. Is there a reason to switch them?

**Comment by marcoscaceres** [comment]
Closing as answered. No reason to make the change was given.
