### ISSUE TITLE
Spec examples do not include `request()`

### ISSUE THREAD

**Issue by slightlyoff** [w3c/permissions#144]
It's odd that the examples in the spec do not illustrate usage of `request()`.

**Comment by raymeskhoury** [comment]
We never reached consensus to to ship request(). The fact that it's still in the latest editors draft is problematic given the current state of discussions around it.

**Comment by jyasskin** [comment]
Yeah, I'm way overdue to move it to an incubation: https://github.com/w3c/permissions/issues/83#issuecomment-246564060.

**Comment by marcoscaceres** [comment]
closing as per #83
