### ISSUE TITLE
Request `Fullscreen` state

### ISSUE THREAD

**Issue by RichardMaher** [w3c/permissions#147]
WRT:- https://github.com/w3c/permissions/issues/145 

- Are you also asking for the "display":"fullscreen" feature to be taken out of the manifest?
- Do you want the manifest to trigger the permission request?
- Being installed on the homescreen implicitly grants permission?
- What is the "foo" element in your example above?

**Comment by RichardMaher** [comment]
See also https://github.com/w3c/permissions/issues/26#event-728313860

**Comment by marcoscaceres** [comment]
Closing as out of scope.
