### ISSUE TITLE
Preventing blackmail

### ISSUE THREAD

**Issue by gutsle** [w3c/permissions#171]
Android permissions have evolved to allow a user allowing and denying specific requests made by an application. An application could just ask the user for location data, even though it was irrelevant for the functioning of the application. The application has to be able to deal with requests failing. This is useful because before the changes it was possible for an application to essentially blackmail a user into accepting permissions and refusing installation otherwise.

This problem is even worse on the web where absolutely no trust relationship to opened sites exist.

The question I am positing is: Does this proposal create similar problems?

**Comment by KOLANICH** [comment]
#54

**Comment by jyasskin** [comment]
If you're happy with the new Android model, where users can decline particular permissions but still use the rest of an application, you should also be happy with the web model including `permissions.query()`. It's definitely possible for an application to say "if you don't grant this permission you can't use any of the site", on both Android and the web, but the structure of the APIs doesn't encourage it.

**Comment by KOLANICH** [comment]
in fact any structure allowing easy determination if the permission is granted does

**Comment by gutsle** [comment]
@jyasskin This may not be in mainstream Android but at least some ROMs allow pretending that the data is available but returning for example an empty list of contacts. Shouldn't the API not only "not encourage" blackmail but make it more difficult?

@KOLANICH 
I agree and therefore this specification should mandate that supporting this API also means supporting faking data, right?

**Comment by KOLANICH** [comment]
@gutlse, there some emploees of the company taking major share of browser market in W3C. That company somewhen proposed to allow webapps to use sensors without permissions. The company seems to be interested somehow in allowing web apps spying on users. Maybe because it has own analytics and advertising services.

**Comment by wseltzer** [comment]
@KOLANICH the accusations in the message above go beyond the scope of appropriate discussion for W3C forums. Please do not do so again. This issue is closed.
