### ISSUE TITLE
Using Web IDL to describe WebDriver JSON is a bit unusual

### ISSUE THREAD

**Issue by foolip** [w3c/permissions#174]
https://w3c.github.io/permissions/#automation

The use of a Web IDL dictionary can be understood by readers I think, but it's a bit of a mismatch. The "converted to an IDL value" algorithm in particular converts ES values to IDL values, but the input is a string. It *would* make sense if `JSON.parse()` were somehow involved, but the WebDriver implementation won't itself have a JS engine inside of it.

@kereliuk @jugglinmike

**Comment by foolip** [comment]
In another context where Web IDL was used unconventionally (can't find it) @domenic suggested using https://infra.spec.whatwg.org/#structs. Here I don't think that's the answer, but I would be interested to hear @domenic's thoughts.

**Comment by domenic** [comment]
https://github.com/whatwg/infra/issues/159 is the issue where we're thinking of tackling this. Let me add a bit more of a comment there summing things up.

**Comment by foolip** [comment]
Sounds like you suggested this, @jyasskin, WDYT?

**Comment by jyasskin** [comment]
I'm not sure if I'm reading https://w3c.github.io/webdriver/#processing-model correctly, but I see:

> Let parse result be the result of [[parsing as JSON](https://w3c.github.io/webdriver/#dfn-parsing-as-json) with request’s body as the argument.
> ...
> let parameters be parse result.
> ...
> running the remote end steps for command with an argument named url variables whose value is url variables and an additional argument named parameters whose value is parameters.

So, I think we *do* start with a Javascript object that's the output of `JSON.parse()`, which it makes sense to use WebIDL on. I hope it's not observable if WebDriver implementations lacking a JS engine go directly from the string to the dictionary object. 

That said, whatwg/infra#159 makes some good points about this being the wrong semantics in some cases. I think I'd weakly vote for keeping the current text until that's resolved, and then switching to it.

**Comment by foolip** [comment]
Thanks, I did not spot the "parsing as JSON" which makes this actually work.

**Comment by marcoscaceres** [comment]
closing. We can update if whatwg/infra#159 eventually lands.

**Comment by domenic** [comment]
whatwg/infra#159 landed, to the extent needed for this at least.
