### ISSUE TITLE
Background GeoLocation

### ISSUE THREAD

**Issue by OpenLocationServices** [w3c/permissions#179]
Are any vendors willing to implement it? There are many use cases for this, and I'm sure they've already been discussed. 

Is there any interest to initially put this behind a flag to be enabled manually? This is certainly very useful information for apps that need location in background. Apps like uber continue to record location even after 5 minutes of completing the trip for safety reasons. 
Apps for children's safety that help parents keep a watch on their kids would also like it. There are several uses.

**Comment by KOLANICH** [comment]
I prefer background geolocation be disabled unconditionally. At least untill a reasonable way of faking permissions is developed and implemented in all browsers. I don't want to get "enable background geolocation or **** off" somewhen.

**Comment by AhsanE** [comment]
Is this the way discussion goes on at the W3C?

**Comment by OpenLocationServices** [comment]
> I don't want to get "enable background geolocation or **** off" somewhen.

Is this how discussion goes on here?

**Comment by marcoscaceres** [comment]
Deleted offending comment. Please refrain from using foul language as it’s in violation of the w3c code of conduct (yes, **** counts, as it’s clear what was implied).

**Comment by dveditz** [comment]
What do you mean by background geolocation? Once the permission is granted aren't all the requests in the background? I can guess several different things that you might want, and maybe am not guessing correctly:
a) permissionless geolocation
b) script that lives on and gets geolocation even after the page/tab is closed
c) ???

I can see the use in "Apps" (services, really) on a smartphone. Having trouble imagining a good use in a web page.

**Comment by jyasskin** [comment]
The permissions repository isn't a great place to ask for this, so I'm going to close this issue. https://discourse.wicg.io/t/proposal-expose-geolocation-to-service-workers/2588 is probably a better place to discuss it.

@dveditz That thread also has some use cases.
