### ISSUE TITLE
Conditional permissions

### ISSUE THREAD

**Issue by martinthomson** [w3c/permissions#189]
As the use of the tools in this spec are being used for more different features, we're starting to see the gaps.

For instance, requests for media autoplay (#172) and fullscreen (#26) highlight the potential need for conveying additional permissions, specifically engagement.  The storage access API implemented variously by Apple and Mozilla also shows how engagement with the origin is a necessary precondition for even showing a permissions prompt, and it might be necessary - even with permission - to have engagement before the associated action can be triggered.

The API currently manages this poorly.  If a permission is queried, what should it say if a request might be an outright denial in the absence of an engagement gesture, but a prompt if there is a recent click or key press?

The permissions state really isn't sufficient for this.

**Comment by miketaylr** [comment]
I think this is valuable idea to explore - my proposal is to close here, but we keep https://github.com/w3c/permissions/issues/377 open as a pointer to it, if and when a UA decides they need the infrastructure to implement conditional permissions.
