### ISSUE TITLE
Add "screen-wake-lock" permission type

### ISSUE THREAD

**Issue by kenchris** [w3c/permissions#192]
https://github.com/w3c/wake-lock/issues/184

**Comment by rakuco** [comment]
@marcoscaceres I can tackle this, but need clarification on the best approach: should I just point to what we have in the Wake Lock API or is it better to move https://w3c.github.io/wake-lock/#the-wakelockpermissiondescriptor-dictionary over to this spec?

**Comment by kenchris** [comment]
ping @marcoscaceres

**Comment by marcoscaceres** [comment]
Sent PR https://github.com/w3c/permissions/pull/247
