### ISSUE TITLE
Add "background-playback" permission type?

### ISSUE THREAD

**Issue by mantou132** [w3c/permissions#193]
Users may not want the browser to make sounds in the background, but some applications need to play in the background, such as music players.

**Comment by marcoscaceres** [comment]
What is the mechanism today that is used to request this ability? Does one exist? I see Chrome has:

<img width="660" alt="Screen Shot 2021-06-24 at 3 43 54 pm" src="https://user-images.githubusercontent.com/870154/123208747-fd39b300-d502-11eb-9018-e24f3ca36352.png">

@mounirlamouri, do you know?

**Comment by marcoscaceres** [comment]
this is no longer in scope of this particular spec.
