### ISSUE TITLE
tcp/udp permission

### ISSUE THREAD

**Issue by jimmywarting** [w3c/permissions#195]
is something powerful as tcp/udp permission planned somewhere?

I know there is some Security implications of allowing websites to open TCP sockets. But i thought i would ask if it would ever become available under a permission request at least.

Not being able to make any network request that you like is PWA killer in my case and it's why i would have to look into building native applications instead.

**Comment by marcoscaceres** [comment]
Understood, unfortunately no plans. Tcp/udp sockets are too dangerous for the web. Best we can do is web sockets right now.
