### ISSUE TITLE
Redundant assertion

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/permissions#2]
This assertion is redundant.

> A Permission dictionary MUST contain a name field which represents the permission's identifier.

The WebIDL already says this. 

(I also think we should should just drop the Permission Dictionary, as we discussed yesterday)

**Comment by mounirlamouri** [comment]
I think @ClaesNilsson is right. We need to keep ```Permission```. It's not clear to me what the redundancy is about. Please, reopen if I missed something.
