### ISSUE TITLE
PermissionName not defined as proper IDL block

### ISSUE THREAD

**Issue by tidoust** [w3c/permissions#205]
(From https://github.com/tidoust/reffy-reports/issues/47)

I suspect that was done on purpose given the [comment in the source](https://github.com/w3c/permissions/blob/master/index.bs#L605), but the [`PermissionName` definition](https://w3c.github.io/permissions/#permission-registry) lacks a `class="idl"` attribute. The consequence is that it is not picked up as a Web IDL definition by Bikeshed.

In turn, this means that the interface neither appears in the [IDL index](https://w3c.github.io/permissions/#idl-index) at the end of the specification, nor in the [IDL extract in Web Platform Tests](https://github.com/web-platform-tests/wpt/blob/master/interfaces/permissions.idl).

**Comment by jyasskin** [comment]
I believe this was fixed by #229.
