### ISSUE TITLE
Can `Permission task source` be exported?

### ISSUE THREAD

**Issue by yoavweiss** [w3c/permissions#206]
I'd like to use the permission task source in https://github.com/WICG/ua-client-hints/pull/101, in order to post a task that may be waiting on permissions (so a task to get information about the user agent).

Would it be possible to export the `permission task source`? If so, I can send a PR.

**Comment by jyasskin** [comment]
Task sources are black magic to me, so I don't object to exposing it if it's useful to other specs. This comes from https://github.com/w3c/permissions/commit/9cb5f82f86491ce3f316ea224dbb382013d546e5 in 2014.
