### ISSUE TITLE
Script origin bound permissions

### ISSUE THREAD

**Issue by nuxodin** [w3c/permissions#211]
While following the current fingerprinting debate, I made the following consideration:

Would it be possible to grant permissions only for domains of the corresponding script?

Let's assume the website runs on trasted-domain.com

trasted-domain.com/main.js:
```js
await navigator.permissions.query({ name: "geolocation" })

// -----------------------------------------------------------------------------
// |  would you like to allow access to geolocation for trusted-domain.com?    |
// -----------------------------------------------------------------------------
```

tracker.com/main.js:
```js
await navigator.permissions.query({ name: "geolocation" })

// -----------------------------------------------------------------------------
// |  Attention, the access is requested from a different domain!              |
// |  would you like to allow access to geolocation for trusted-domain.com?    |
// -----------------------------------------------------------------------------
```

Or better still, it fails in silently anyway?

To make it backwards compatible with the implemented state, would an option `scriptOriginBound:true` be a possibility?
The implementers might only want to allow access with this option enabled.

trasted-domain.com/main.js:
```js
await navigator.permissions.query({ name: "geolocation", scriptOriginBound:true })
```

I don't know if this has already been discussed, but I could not find anything.

**Comment by clelland** [comment]
Permissions Policy attempts to solve this, though at the document origin level, not script origin.

Implementing this based on script origin would be difficult, and likely ineffective. If tracker.com can get you to run their script on your page, then they can do things other than requesting permission directly. (They can write new scripts directly into the DOM, either directly or indirectly, and can have geolocation data passed silently between scripts, as they'd be running in the same global environment).

Solving this with the current JS execution model would probably require taint tracking at least, to ensure that the command to request permission really did originate in the assumed origin, if it's possible at all. Executing third-party scripts is really giving  lot of trust to whoever controls that code.

**Comment by nuxodin** [comment]
Yes true, it is almost impossible to prevent the requested data from being leaked with access to the global-scope.

**Comment by marcoscaceres** [comment]
Agree, that current approach of using Permissions Policy is the best we have right now. We probably want to see how that plays out in browsers over the next few years as that gets deployed. Closing this for now as there is no further action to be taken, but please feel free to continue discussing.
