### ISSUE TITLE
Privacy Considerations

### ISSUE THREAD

**Issue by wseltzer** [w3c/permissions#22]
Since the state of a persistent permission can be an element of user-agent fingerprinting, exposing numerous permissions to query could make a user's behavior more linkable. Implementors may want to consider enabling users to block (globally or selectively) the querying of permission states.

**Comment by mounirlamouri** [comment]
Thanks for filling the issue. It should be fixed by https://github.com/w3c/permissions/commit/312a2117c1c5a39849a27e87bdaa7ebe36446519
