### ISSUE TITLE
chore: Turn on `Assume Explicit For`

### ISSUE THREAD

**Issue by jyasskin** [w3c/permissions#220]
As discussed in https://github.com/w3c/permissions/pull/217#discussion_r459769197, [`Assume Explicit For`](https://tabatkins.github.io/bikeshed/#metadata-assume-explicit-for) forces us to me more precise about our link targets, which will remove two ambiguities about which reference was meant. It'll take fixes to about 20 places in the spec, so I'm not doing it right now, but it's a good idea next time someone wants to do some easy editorial work.

**Comment by marcoscaceres** [comment]
Closed via https://github.com/w3c/permissions/commit/b3a772a44fd71cbb1fb55495e10f00123ae2c945
