### ISSUE TITLE
Write a Security Considerations section

### ISSUE THREAD

**Issue by jyasskin** [w3c/permissions#221]
The spec currently has a [Privacy Considerations](https://w3c.github.io/permissions/#privacy-considerations) but no Security Considerations section, which causes a Bikeshed warning. Bikeshed is probably right that we should write some security considerations.

**Comment by marcoscaceres** [comment]
closing as the spec has "Security and privacy considerations" section. 

But it should be expanded, but we have other specific issues open around that.
