### ISSUE TITLE
Gauging interest in a Permission Handler API?

### ISSUE THREAD

**Issue by jcayzac** [w3c/permissions#224]
Hello,

The Permission API currently [freezes](https://www.w3.org/TR/permissions/#enumdef-permissionname) the list of supported permission names. Has there already been any discussion about opening this to 3rd-party permission handlers, similarly to how the [Payment Handler API](https://www.w3.org/TR/payment-handler/) allows 3rd parties to install new payment instruments for use with the Payment Request API, using [service worker registration](https://www.w3.org/TR/service-workers-1/#service-worker-registration-concept)?

This would allow web developers to use a single API to query permissions not only for the APIs and features provided by browser vendors but also APIs and features provided e.g. by non-browser applications rendering 3rd-party web content using webviews, or by any PWA registering its service worker.

One practical example is webview-based "mini-apps" running in a native application. I am currently building such a platform, and allowing 3rd-party web developers to check for end-user permissions using the standard Permissions API they're familiar with make for a better design overall. Similarly to how the Payment Handler API operates, I can imagine a near future where web developers creating progressive web apps compatible with our mini-apps platform would simply make calls like:

```js
const canAccessOrderHistory = await navigator.permissions.query({
  handler: 'https://account.rakuten.com/me',
  name: 'order-history',
})

const canAccessUserInfo = await navigator.permissions.query({
  handler: 'https://account.rakuten.com/me',
  name: 'profile',
  info: ['name', 'phone', 'email'],
})
```

…and where the returned promise would produce an indeterminate `null` value if there is no registered handler by the specified name.

Do you see any major problem with the idea? Do you think this could be part of a Permission API L2 draft, or that it should be a separate document (like Payment Handler is separate from Payment Request) ?

Thank you.

@w3c/permissions-admins @mounirlamouri @jyasskin @marcoscaceres

**Comment by jcayzac** [comment]
Just to clarify: the above code can already be supported by hooking onto `navigator.permissions.__proto__` but its being non-standard means there is no value in providing this over simply handling permission manager with a completely proprietary interface.

**Comment by marcoscaceres** [comment]
Although there is overlap, I think the Permission API serves a different purpose (specific for "powerful features" and permission policy checks)... "payments" itself being a powerful feature. 

In the future, I guess we could look at something like:

```JS 
await navigator.permissions.query({
  name: "payments",
  data: { 
     handler: 'https://account.rakuten.com/me',
     name: 'order-history',
  }
}
```

But being able to communicating with an arbitrary third-party payment handler over this mechanism feels very unpalatable to me.

**Comment by marcoscaceres** [comment]
Closing as answered.
