### ISSUE TITLE
[question] permission scope

### ISSUE THREAD

**Issue by akosyakov** [w3c/permissions#226]
What is the scope permission? Is it always the origin of page? 

We have a use case when permission should be granted for root domain to allow asking permissions over and over for different subdomains: https://github.com/gitpod-io/gitpod/issues/2177#issue-742569726 Is it allowed by the spec somehow?

Sorry if it is not right place to ask.

**Comment by marcoscaceres** [comment]
Sorry this didn't get answered. Permissions are origin bound. Having different subdomains will result in the browser treating them as different origins.  

This may change a bit with integration with "policy container" https://github.com/w3c/permissions/issues/240
