### ISSUE TITLE
Should we SecureContext the API

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/permissions#235]
Apart from MIDI and Notifications, there doesn't seem to be a strong case to expose this API in non-secure contexts. 

Should we "secure" it?

**Comment by clelland** [comment]
I think that this API is an important part of allowing pages to reason about what features are and are not available; I don't see the harm in allowing pages to query, even if the answer is a guaranteed *no* every time. We're already removing the underlying features themselves; keeping this API means that developers don't need to write special HTTP-only code to determine that.

As an additional point, If we move to merge some of the permissions policy API into this API, then there will likely be more features that are usable in non-secure contexts. (Things like fullscreen, picture-in-picture, storage access). I think it would still make sense to be able to query those in any context where they are available.

**Comment by jyasskin** [comment]
I was trying to poke holes in @clelland's argument, by thinking of any privacy- or security-relevant abilities a page gets by just knowing its permission state. The one that comes to mind is ads learning whether they can silently check the user's location, but that's plugged by geolocation being `[SecureContext]`, so it's not support for restricting the permissions API itself.

**Comment by marcoscaceres** [comment]
Ok, yeah. I agree with what @clelland is saying.
