### ISSUE TITLE
Add "web-share" to PermissionName?

### ISSUE THREAD

**Issue by saschanaz** [w3c/permissions#236]
Web Share uses the string ["web-share"](https://w3c.github.io/web-share/#permissions-policy) for the permission name but it's not in [the enum](https://w3c.github.io/permissions/#permission-registry).

**Comment by marcoscaceres** [comment]
As web-share always requires user action, and it shows a  dialog (i.e., doesn't prompt, like, for example Geo), we don't need to add it to the enum.
