### ISSUE TITLE
Move to using Echidna

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/permissions#24]
Need to set up automated publishing after FPWD.

**Comment by marcoscaceres** [comment]
Will do this later this week.

**Comment by marcoscaceres** [comment]
* [ ] add editor IDs. 
 * [ ] Find link to WD decision to use auto-pub model. 
 * [ ] [encrypt key via travis](https://github.com/w3c/echidna/wiki/Setting-up-Echidna-as-a-GitHub-hook).

**Comment by mounirlamouri** [comment]
Marcos, is there something I can help with here?

**Comment by jyasskin** [comment]
FYI, https://www.w3.org/TR/permissions/ is still out of date.

**Comment by marcoscaceres** [comment]
Currently [failing PubRules](https://www.w3.org/pubrules/?url=https%3A%2F%2Fw3c.github.io%2Fpermissions%2F&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004). 

We need to update some of the bikeshed metadata.

**Comment by jyasskin** [comment]
We need the Travis script to fail when PubRules is broken, so that we get 'x's on the commit log.

**Comment by jyasskin** [comment]
https://lists.w3.org/Archives/Public/public-tr-notifications/2016Sep/0042.html is fun. Trying to include a '&' in the URL for Echidna to fetch makes it omit the error details. We need the '&md-status=WD' in order to generate a pubrules-compliant WD.

**Comment by jyasskin** [comment]
@tabatkins, is there an https://api.csswg.org/bikeshed/ endpoint we should be using to publish to Echidna using `bikeshed echidna`? Otherwise, I guess we could use `https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/w3c/permissions/master/index.bs&md-status=WD&md-prepare-for-tr=true` as our url.

**Comment by tabatkins** [comment]
No, we don't yet have a remote endpoint for submitting to Echidna. Would be useful.
