### ISSUE TITLE
Add "fullscreen"

### ISSUE THREAD

**Issue by annevk** [w3c/permissions#26]
https://fullscreen.spec.whatwg.org/ does not seem covered.

**Comment by annevk** [comment]
Let's leave this open until new fullscreen UI is out.

**Comment by jyasskin** [comment]
Whenever we decide we want this, https://fullscreen.spec.whatwg.org/ should `<dfn>` the enum value, and then this spec can add it to the list.

**Comment by annevk** [comment]
Fullscreen won't be permission-gated. Just gesture-gated.
