### ISSUE TITLE
Move permissions out to each spec

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/permissions#263]
The Permissions registry seems a roundabout way to maintain things.... I think we definitely keep the various parts other specs need to define (plus an example of what other specs need to do), keep the enum, but then move all permission descriptions to their respective specs. 

That allows this spec to "gate-keep" the main enum for the API, but allows other specs to define their own permissions. 

TODO:
* [x] #296
* [x] #307
* [x]  "background-fetch", (https://github.com/w3c/permissions/issues/295)
* [x] #308
* [x] #317
* [x] #323
* [x] #322
* [x]  "geolocation" (https://github.com/w3c/geolocation-api/pull/105/)
* [x] #321
* [x] #326
* [x] #294
* [x] #328
* [x] #291
* [x] #329
* [x] #293
* [x] #319
* [x] #320
* [x] #330

**Comment by jyasskin** [comment]
I tried to do this at some point by having each spec <dfn> its PermissionName enum value, but IIRC Bikeshed didn't autolink from https://w3c.github.io/permissions/#enumdef-permissionname to definitions outside the current spec, and writing that enum manually broke reffy's IDL parser. https://w3c.github.io/permissions/#bluetooth is the maximum amount of "define everything in the feature's spec" that seemed possible, but going that far seems like a good idea.

**Comment by marcoscaceres** [comment]
My plan is to separate the concept of a "permission" ([a new definition type](https://github.com/speced/spec-dfn-contract/issues/8)), and those independent of the enum values. Specs now routinely define an "Integration with Permissions Policy" section where they identify the permission string they are using. Our spec will just define the enum and values, but not claim to be the permission itself. 

That way, we can avoid the auto-linking issues (🤞) and everyone can own their own stuff.

**Comment by marcoscaceres** [comment]
Where applicable,  we should add a "Permission prompt" heading/section to specs and add: 

 * it is a default power feature,
 * and any step/algorithms there...
