### ISSUE TITLE
Add an introduction section? 

### ISSUE THREAD

**Issue by miketaylr** [w3c/permissions#274]
Should there be an introduction? Right now, the spec just jumps into examples.

**Comment by marcoscaceres** [comment]
The intro is not required, but it would be nice. I think it would be amazing if the intro covered the following things. Bonus would be for us to slap together a diagram. Something like Chrome's (without the usage data):

![Screen Shot 2021-08-31 at 11 46 31 am](https://user-images.githubusercontent.com/870154/131428297-8e98ed00-f1f6-4763-a598-c68cb92323a9.png)
 
And something that show and actual prompt associated with a powerful feature:

![Screen Shot 2021-08-31 at 11 50 39 am](https://user-images.githubusercontent.com/870154/131428638-2e49cdab-89fb-4334-aa1a-975f998a9365.png) ![Screen Shot 2021-08-31 at 11 53 13 am](https://user-images.githubusercontent.com/870154/131428845-96b83263-37c3-4127-8c67-804ad8715758.png)

General model: 
 * Some, but not all, specs can identify themselves as a powerful feature. 
 * Powerful features are web platform features/APIs that require user consent before they can be used. Consent its generally mediated (or gotten) via browser UI. 
 * A permissions thus captures the state of user consent to use a particular feature.
 * Users (or the user agent on their behalf) retain control of the permission, and may deny access to a powerful feature at any time, for any reason. 
 * Further, user agents can limit how long a permission grant last for (e.g., until the user closes the tab, for 1 day, for a week, forever). It's generally up to the user agent.

For specs:
  * Common infrastructure for requesting permission, prompting, etc.  
  
Developer angle:
 * Some powerful features lack a means to check the permission state. 
 * This API provides a way to query a permission's state, without interrupting the user by showing them a prompt. 
 * It also allows developers to monitor for state changes to permissions, via DOM events on `PermissionStatus`.

**Comment by jyasskin** [comment]
There was some introductory text before https://github.com/w3c/permissions/commit/f439e8513666c5b7d031f029e0481b80e5163c34#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L64 removed it. I don't think that change was reviewed anywhere?

**Comment by marcoscaceres** [comment]
I moved that text as part of the editorial rewrite/reorganization I did recently.

Regardless, a new informational introduction as I described above would be really nice. IMO, the old “Scope” section wasn’t working as well as it could as an introduction, so I’m excited to work with @miketaylr on a new one. Would be great to get your review @jyasskin.

**Comment by miketaylr** [comment]
@marcoscaceres maybe easier to bikeshed text in a google doc, so here's a draft of me stealing your outline:

https://docs.google.com/document/d/1TsBwLyLkcNsnFi74FNNiCP5gw2c-xynJRHt-Z8jCiVM/edit#bookmark=id.t0tv0ul359oe

Feel free to comment, or request edit access!
