### ISSUE TITLE
Link to CONTRIBUTING.md from README.md

### ISSUE THREAD

**Issue by miketaylr** [w3c/permissions#288]
We could make it more obvious how to contribute, if you're just looking at README (GitHub provides links, but I never look for those.

To fix this, we could link to https://github.com/w3c/permissions/blob/main/.github/CONTRIBUTING.md from the README file.

**Comment by MiTo0o** [comment]
This sounds like something I could work on, can I take this?

**Comment by miketaylr** [comment]
> This sounds like something I could work on, can I take this?

That would be great! Thanks!
