### ISSUE TITLE
Support for background sync (one-off and periodic)

### ISSUE THREAD

**Issue by KenjiBaheux** [w3c/permissions#29]
The Background sync IDL is being updated: we are moving toward a design where periodic and one-off background sync would be independent. The UA may place these behind separate permissions.

https://github.com/jakearchibald/BackgroundSync/blob/mvp/idl.md (Review on-going)

Strawman:

``` javascript
enum PermissionName {
    "geolocation",
    "notifications",
    "push",
    "midi",
    "backgroundsync"
};

dictionary BackgroundSyncPermissionDescriptor : PermissionDescriptor {
    enum BackgroundSyncType type;
};

enum BackgroundSyncType {
   "one-off",
   "periodic"
};
```

cc/ @jakearchibald @jkarlin @annevk

**Comment by annevk** [comment]
Shouldn't we just use two permission names to keep it simple? "sync" and "periodicsync", just like we name them in the tentative specification.

**Comment by KenjiBaheux** [comment]
Sounds reasonable. 
We'll have to check what that would like if we rename the API.
https://github.com/slightlyoff/BackgroundSync/issues/76

**Comment by jyasskin** [comment]
If y'all want a new PermissionName enum value beyond [`"background-sync"`](https://w3c.github.io/permissions/#dom-permissionname-background-sync), please define it in https://wicg.github.io/BackgroundSync/spec/, and then ping here to get it added to the list in the enum. Ideally, you should also take over the definition of the `"background-sync"` value too.

**Comment by marcoscaceres** [comment]
closing as answered... waiting on bgsync to progress and get wider adoption.
