### ISSUE TITLE
Geolocation API does not leave the page unaware of permission status

### ISSUE THREAD

**Issue by mvano** [w3c/permissions#30]
The Geolocation API does not leave the page entirely unaware of the permission status. It has a PositionError with a code that can have the value PERMISSION_DENIED:
http://www.w3.org/TR/geolocation-API/#permission_denied_error

I would agree that determining the status using the Geolocation API is harder though. Some rephrasing in section 3 seems appropriate.

**Comment by marcoscaceres** [comment]
not sue exactly what you are trying to do here tho? Check the permission state?

**Comment by mounirlamouri** [comment]
Fixed by https://github.com/w3c/permissions/commit/c718502f96d94b65acd04bbe39fc2a16f9039a33
