### ISSUE TITLE
Proposals: Drop "Powerful features registry" and PermissionName enum

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/permissions#314]
I'd like to propose we drop the `PermissionName` enum entirely and switch it to a `required DOMString` instead. 

The rationale for the change is that the Permission Spec is acting as a "gate-keeper" for other specs that may never get broadly supported. 

For example, Gecko only supports the following 4:
https://github.com/mozilla/gecko-dev/blob/43d18f9b44c9967029684aa66d0ad70dee3e89e5/dom/webidl/Permissions.webidl#L10-L16

WebKit has the following as a stub (doesn't actually reflect what is supported):
https://github.com/WebKit/WebKit/blob/cb1203bad562777ee3c25b4eb49ef16477385d1b/Source/WebCore/Modules/permissions/PermissionName.idl#L28-L43

What I propose we do instead is allow each spec to define its power-feature name (e.g., "geolocation"), which is then passed to the algorithms or API as appropriate. We are are already doing in practice.

This change would be backwards compatible, in that implementers could retain their current `PermissionName` enums for implementation purposes. For `.query()`, we would just make `PermissionDescriptor.name` behave like enum. 

It would also mean we no longer need to enum values "at risk" in our spec. 

Any objections?

**Comment by jyasskin** [comment]
Would it make sense to move this list to something on the new [Registry track](https://www.w3.org/2021/Process-20211102/#registries)? The "at risk" permissions could be "provisional" in IANA terminology, with a first-come-first-served policy, while the rest could be "standard" with a CR or REC (or equivalent in another SDO) required.

**Comment by marcoscaceres** [comment]
Not sure we need anything as heavyweight as a formal registry - specially if it’s specs themselves defining their feature name/string. However, we could just keep a wiki page of known powerful features.

**Comment by dveditz** [comment]
Please, don't drop the registry. One of the points of a registry is so the basic spec is NOT a gate-keeper, so sure, drop the enum from the Permission spec itself. But the other point of a registry is so that like items are gathered in one place for documentation and discovery.  I don't care whether it's a WG document maintained by you through PRs from other specs, an official IANA thing, or an official W3C "Registry Track" document, as long as wherever it is is referenced in the Permission spec itself.

**Comment by miketaylr** [comment]
Registry track doc that @jyasskin mentions seems like a useful place to document things.

**Comment by marcoscaceres** [comment]
Yeah, after some more consideration, I'm warning up to @jyasskin's idea of having the separate registry. Updating the Registry is not much more work than updating a wikipage... it's all markdown after all. I'll make that happen.

**Comment by marcoscaceres** [comment]
Ok, rough draft:
https://w3c.github.io/poweful-features-registry/

I've reached out to the chairs and team to coordinate publish it.
