### ISSUE TITLE
Can we drop the allowed in non-secure contexts flag?

### ISSUE THREAD

**Issue by miketaylr** [w3c/permissions#315]
After Notifications loses it, are there any other powerful features that work in non-secure contexts?

https://w3c.github.io/permissions/#dfn-allowed-in-non-secure-contexts

https://github.com/whatwg/notifications/pull/175

**Comment by marcoscaceres** [comment]
Yes, I think we should be ok to drop it... Web Bluetooth references it, but to say that it doesn't use it. 

https://github.com/search?q=org%3Aw3c+dfn-allowed-in-non-secure-contexts&type=code

**Comment by miketaylr** [comment]
Thanks - once we get the Notifications PR landed, I can send in a PR to Bluetooth to remove the reference.
