### ISSUE TITLE
Ensure "bluetooth" is integrated into Web Bluetooth spec

### ISSUE THREAD

**Issue by miketaylr** [w3c/permissions#317]

**Comment by miketaylr** [comment]
At a quick glance, this looks pretty good: https://webbluetoothcg.github.io/web-bluetooth/#permission-api-integration - maybe just a few tweaks needed.

**Comment by marcoscaceres** [comment]
oh yes, that looks great. Probably just need the powerful feature name.

**Comment by marcoscaceres** [comment]
actually, it's already there... missed it on the first reading.

**Comment by miketaylr** [comment]
Created https://github.com/WebBluetoothCG/web-bluetooth/pull/565, which is pretty small.

**Comment by miketaylr** [comment]
PR was merged.
