### ISSUE TITLE
Ensure "gyroscope" is integrated into Gyroscope API

### ISSUE THREAD

**Issue by miketaylr** [w3c/permissions#321]

**Comment by miketaylr** [comment]
I guess it could go here, https://www.w3.org/TR/gyroscope/#model

**Comment by rakuco** [comment]
Proposed patch: w3c/gyroscope#47

**Comment by miketaylr** [comment]
> Proposed patch: [w3c/gyroscope#47](https://github.com/w3c/gyroscope/pull/47)

Ah nice!

**Comment by miketaylr** [comment]
PR landed.
