### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Titieom11** [w3c/permissions#343]
https://coinpromocodes.wpcomstaging.com/2021/08/22/why-chinese-banks-are-adding-digital-yuan-to-apps-heres-what-you-need-to-know/?amp

**Comment by clelland** [comment]
Closing as off-topic.

**Comment by miketaylr** [comment]
(i've reported this user as a spammer to github, but i guess they haven't blocked them yet)

**Comment by marcoscaceres** [comment]
I blocked them at the org level.
