### ISSUE TITLE
Automation: Need two more steps to handle closed browsing context and user prompts

### ISSUE THREAD

**Issue by Honry** [w3c/permissions#347]
This issue was firstly raised up by @JohnChen0. (see his [comments](https://github.com/w3c/sensors/pull/369#discussion_r234735701 
).)

Any WebDriver extension command that targets the current or current top-level browsing context, there should be a step _"If the current(or current top-level) browsing context is no longer open, return error with error code no such window"_ near the beginning of the remote end steps. 

Most commands should also handle user prompts(step:  _"Handle any user prompts and return its value if it is an error."_),_ unless there is some specific reason not to do so. When a prompt is shown, browser functionality is severely limited (e.g., JavaScript code can't be run), and may make it difficult to execute the command.

cc/ @jugglinmike

**Comment by marcoscaceres** [comment]
@Honry or @jugglinmike, would appreciate your feedback? 🙏

**Comment by marcoscaceres** [comment]
Closing as the automation part was rewritten, and presumably this is now covered by the new steps.
