### ISSUE TITLE
Remove global variables

### ISSUE THREAD

**Issue by annevk** [w3c/permissions#35]
A bunch of algorithms invoke each other without passing along the variables clearly. It's unlikely this English would pass a compiler.

**Comment by annevk** [comment]
As an example, `query()` invokes "create" in step 4 and passes it two variables yet "create" only accepts one. Since the first argument "create" accepts is a permission and it is passed a global object this would likely crash if I were to attempt to implement this.

**Comment by mounirlamouri** [comment]
I fixed the invocation of create: https://github.com/w3c/permissions/commit/485a7ceb918abb2826c4c08d55622616d2f48801

Please, reopen or file another bug if you see another instance where the passed arguments are wrong.

**Comment by annevk** [comment]
Please make it easier to file issues then by including something like file-issue.js as other specifications do.
