### ISSUE TITLE
status of this document: reached FPWD

### ISSUE THREAD

**Issue by npdoty** [w3c/permissions#36]
>  This document is defining a low footprint API that was agreed upon in public-webapps mailing-list discussions and TPAC meetings. It has not yet reached a FPWD. 

Doesn't seem quite right, given http://www.w3.org/TR/permissions/. 

(I'm not sure about "agreed upon" either ;))

**Comment by mounirlamouri** [comment]
Fixed by https://github.com/w3c/permissions/commit/809ddc7c5815a1d3c5f1d7ec86bc981828552bd5
