### ISSUE TITLE
"Prompt the user to choose" should let caller decide how many results are allowed.

### ISSUE THREAD

**Issue by jyasskin** [w3c/permissions#375]
https://w3c.github.io/permissions/#prompt-the-user-to-choose currently insists on picking exactly one of the available options. 

The call @inexorabletash is adding in https://github.com/WICG/local-font-access/pull/76 would like to let the user pick many options, so we should change the wording here to allow that.

https://html.spec.whatwg.org/multipage/input.html#show-the-picker,-if-applicable (for `<input type=file>`), which was a model for the picker design in this spec, also allows users to pick multiple options, so if we ever want to retrofit that to call into the permissions spec, that'll also require this change.

**Comment by miketaylr** [comment]
The relevant bit of spec text from the PR is 
> [=/Prompt the user to choose=] one or more items from |selectable fonts|, with |descriptor|, and let |result| be the result.

We would just want to say the same thing, "one or more" in the relevant places in https://w3c.github.io/permissions/#prompt-the-user-to-choose. Seems fine to me - I'll discuss with @marcoscaceres in our meeting next week.
