### ISSUE TITLE
Add persistent storage

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/permissions#39]
/CC @annevk

**Comment by mounirlamouri** [comment]
@annevk suggested to expose this as ```storage``` with no more options. I am waiting for more feedback before adding it to the spec.

**Comment by jyasskin** [comment]
This is now in the spec as [`"persistent-storage"`](https://w3c.github.io/permissions/#dom-permissionname-persistent-storage). That can change if `"storage"` is better, although it seems like persistence is actually the key feature.

**Comment by annevk** [comment]
Should I define this in https://storage.spec.whatwg.org/#persistence instead?

**Comment by jyasskin** [comment]
Yes please. Once you do that, I'll remove the definition from this spec and just link there.

**Comment by annevk** [comment]
Done. @tabatkins is https://storage.spec.whatwg.org/ indexed by Shepherd and friends?

**Comment by tabatkins** [comment]
yup
