### ISSUE TITLE
Align internal states with enums

### ISSUE THREAD

**Issue by annevk** [w3c/permissions#392]
Instead of Denied, let's use "denied". Same for the others. I don't think we need to distinguish these.

**Comment by marcoscaceres** [comment]
Ok, so effectively just use the enum value everywhere...

**Comment by marcoscaceres** [comment]
@annevk, I put together two different approaches to consider:

 * https://github.com/w3c/permissions/pull/400
 * https://github.com/w3c/permissions/pull/399 

I think [400](https://github.com/w3c/permissions/pull/400) is better, as: 

1. won't break other specs
2. still allows distinguishing between concept and enum value (where needed in algorithms)
3. meets the goal of having single "thing" usage throughout the spec. 

WDYT? Or should we use something different? 

(another limitation with the {{ PermissionState/"whatever" }} solution is that ReSpec doesn't currently support aliasing them ... e.g., if we wanted to write "The app [=grants=] the X some Y".)

**Comment by annevk** [comment]
Yeah, 400 seems right. Except you want "`prompt`" (i.e., using `<code>`) for formatting.
