### ISSUE TITLE
A "dismissed" state

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/permissions#4]
Having read over the spec again, and in light of [Mozilla Bug 675533](https://bugzilla.mozilla.org/show_bug.cgi?id=675533), think we might need a `dismissed` state. Dismissed differs from denied, in that the permission prompt was discarded and no decision was made. 

I know it overlaps with `prompt`, but prompt really means "undecided" or not yet asked. But that's a different bikeshed.

**Comment by QuentinFchx** [comment]
I'm not sure we need a specific state for this. `prompt` is enough.
Correct me if I'm wrong, but the Firefox issue (and the general "Not _now_" problem) is only about: "When the user discard a permission, how long do we wait before asking again ?" aka "How long last _now_ ?".
IMO, it's more an UX problem than an API one.

**Comment by marcoscaceres** [comment]
Yeah, I'm not sure. IMO, the API still needs to give feedback to the developer - specially in the "not now" case.

**Comment by QuentinFchx** [comment]
If we ask for a permission and afterwards its state is still `prompt`, we can deduce the user said "Not now" and that we can still ask again.
Also, I think we need to define what "Not now" implies.
Is it: 
- "Not now until next permission call" ?
- "Not now until tomorrow" ?
- "Not now until the next time I visit the website" ?
- All of them ?

**Comment by mounirlamouri** [comment]
@marcoscaceres I don't thnk ```dismissed``` is a state of the permission. It's a result of the request.

If what you want is to be able to know whether the user dismissed the permission, in an ideal world, you could do:
```js
Permissions.request('foo').then(function(p) {
  if (p.status === 'prompt') {
    // permission was dismissed or ignored
  }
  [...]
});
```
Obviously, we can't do that now because we do not expose a ```.request()``` method.

**Comment by marcoscaceres** [comment]
On March 6, 2015 at 1:48:56 AM, Mounir Lamouri (notifications@github.com) wrote:
> @marcoscaceres I don't thnk ```dismissed``` is a state of the permission. It's a result  
> of the request.
>  
> If what you want is to be able to know whether the user dismissed the permission, in an ideal  
> world, you could do:
> ```js
> Permissions.request('foo').then(function(p) {
> if (p.status === 'prompt') {
> // permission was dismissed or ignored
> }
> [...]
> });
> ```
> Obviously, we can't do that now because we do not expose a ```.request()``` method.

Ok, that works. But shouldn't that be a reject instead? 

I'm mostly just wanting to make sure this gets into the spec somehow (so we can continue to ignore it in Gecko, jk ;) ).

**Comment by mounirlamouri** [comment]
No, the state of the permission after a user dismiss or ignore a prompt is ```prompt``` again, right? The goal of the webpage is to know whether the next call will prompt, isn't?

**Comment by mounirlamouri** [comment]
@marcoscaceres is it okay to close?
