### ISSUE TITLE
Permissions.query takes and object, but magically that is converted to a dictionary

### ISSUE THREAD

**Issue by smaug----** [w3c/permissions#403]
https://w3c.github.io/permissions/#query-method step 2. 
When that step runs, permissionDesc is still an object, yet the text refers to dictionary's _name_ property.

**Comment by annevk** [comment]
Yeah, seems like that ought to be step 5 and get name of _rootDesc_.

**Comment by marcoscaceres** [comment]
Indeed, sent https://github.com/w3c/permissions/pull/404
