### ISSUE TITLE
Add permissions.request()

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/permissions#41]
Ideally, we should be able to request using:
- PermissionDescriptor
- sequence&lt;PermissionDescriptor&gt;

**Comment by domenic** [comment]
I'd really prefer to keep multi-request using Promise.all instead of baking that into the base API.

**Comment by domenic** [comment]
Also, it's unclear what you were considering, but I think rejecting is *not* good for denied permission. It's not exceptional, and causes lots of ergonomic issues when used with `async`/`await`. Here's my main point of comparison:

```js
// always-fulfilled:

if ((await navigator.permissions.request({ name: 'geolocation' }).state === "granted") {
  useGeolocation();
} else {
  tellUserWeAreSadAboutTheirChoice();
}

// rejection on denied:

let ok = false;
try {
  await navigator.permissions.request({ name: 'geolocation' });
  ok = true;
} catch (e) {
  tellUserWeAreSadAboutTheirChoice();
}

if (ok) {
  useGeolocation();
}
```

**Comment by domenic** [comment]
Although, rejecting for true error cases makes some sense. E.g. if you're not [allowed to show a popup](https://html.spec.whatwg.org/multipage/browsers.html#allowed-to-show-a-popup) or if the interface in question doesn't even exist (no geolocation support).

**Comment by alvestrand** [comment]
Is async/await part of Javascript, or is it just at the proposal stage still?

**Comment by domenic** [comment]
It is a proposal.

**Comment by jyasskin** [comment]
[`Permissions.request()`](https://w3c.github.io/permissions/#dom-permissions-request) is in the spec now. It's not implemented for every permission, but that should probably be a per-permission bug.
