### ISSUE TITLE
After granting location permissions to the Geolocation API, it will request permissions again when you refresh the page. This phenomenon is occurring on iOS.

### ISSUE THREAD

**Issue by LeeSangUk2** [w3c/permissions#422]
If you refresh the page after initially granting location permissions, you will be prompted for location permissions again and will need to grant permission again. Currently this only occurs on iOS. Is there a way?

The tested iOS versions are 16.2 and 17.

This is the code implemented when retrieving location information.
```
<script>
        var options = {
            timeout: 15000,
            enableHighAccuracy: true,
            maximumAge: 86400000,
        };

        function success(pos) {
            var crd = pos.coords;

            alert('Your current position is:');
            alert(`Latitude : `+crd.latitude);
            alert(`Longitude: `+crd.longitude);
        };

        function error(err) {
            alert(`ERROR(): `+err.message);
        };
        navigator.geolocation.getCurrentPosition(success, error, options);
</script>
```

**Comment by tomayac** [comment]
(Please note that this is not a support forum.) The geolocation permission on iOS is one-time by default. If you go to Settings and  then Safari, you can toggle "Location Access On All Websites" between "Ask" (default), "Deny", and "Allow".

**Comment by LeeSangUk2** [comment]
When I launched the web from the app, Safari settings did not resolve the issue. How should I solve this?

**Comment by miketaylr** [comment]
It's probably better to ask a question like this on stackoverflow, or if you feel like there's a bug, try reporting it to Apple. Thanks.
