### ISSUE TITLE
Permissions may change status in other ways than "trying to access"

### ISSUE THREAD

**Issue by alvestrand** [w3c/permissions#43]
In getusermedia, we have the device-listing permission, which is granted by successfully gathering access to a device. This changes the return value from enumerateDevices.

The language in this doc seems to assume that you only trigger changes in status (and prompts) by accessing the specific functionality. I think it would be better not to make that assumption.

Not sure how to model this - one way could be to have the status be "denied" when permission is not given, and have it change directly to "granted" when the permission-causing action is taken, never becoming "prompt".

**Comment by jyasskin** [comment]
[`"device-info"`](https://w3c.github.io/permissions/#dom-permissionname-device-info) isn't defined very well, but I think we're no longer making the assumption that permissions are only granted while a site tries to access a feature. Please reopen if something else needs to change about this.
