### ISSUE TITLE
Can 'prompt the user to choose' return deny after some implementation specific timeout?

### ISSUE THREAD

**Issue by youennf** [w3c/permissions#430]
Following on https://github.com/w3c/mediacapture-screen-share/issues/287, it may be good if the spec could add a note stating that the choose selection could return denied without a user action: implementation specific timeout, device sleep...

**Comment by marcoscaceres** [comment]
We discussed this during the editors meeting. We will double check, but we think the algorithm might already support this but we can add an example or clarifying note. 

The question that we have is if this actually ever happens in practice (i.e., does any browser actually time out a permission prompt... we couldn't think of any instances, but does that happen today with `getDisplayMedia()`?)

**Comment by miketaylr** [comment]
It does seem like step 4 of https://www.w3.org/TR/permissions/#prompt-the-user-to-choose already allows this, at least in my interpretation.

**Comment by marcoscaceres** [comment]
Yeah, I agree with what @miketaylr said. That said, we let me just amend the note with a quick example.
