### ISSUE TITLE
Add screen sharing permissions

### ISSUE THREAD

**Issue by martinthomson** [w3c/permissions#45]
This was discussed at the WebRTC/Media Capture meeting.  

The `PermissionDescriptor` will look very similar to that for `getUserMedia`, so this should await the resolution of #10.

The [screen sharing API](https://w3c.github.io/mediacapture-screen-share) has an additional state that the working group wanted to be able to examine using `query()`.  That additional state is needed to indicate that some additional user action is required before prompting the user is even possible.  Understanding why that is necessary depends on understanding the security problems associated with screen sharing.

This will sometimes depend on the parameters passed in the descriptor.  If the JS requests access to a screen rather than a window, this will always be blocked unless the user has taken an action.  In that case, the meaning of "prompt" might be OK.  However, for window sharing, the user prompt will contain a subset of the options unless the extra steps have been taken.  Applications will need/want to know about that.

Queries for screen sharing will never produce a state of "allow", but I expect that that won't be an issue.

**Comment by martinthomson** [comment]
Discussed at TPAC in the Media Capture Task Force: agreed that we wanted to create a code point for this, which will have no additional parameters.  No other special signals are desired.

**Comment by marcoscaceres** [comment]
@martinthomson, what does "create a code point for this" mean in this context?

**Comment by martinthomson** [comment]
"code point" == "the string that you feed the API that identifies the type of permission"

Actually, based on this, I can close this issue.
