### ISSUE TITLE
Add "nfc" to enum PermissionName

### ISSUE THREAD

**Issue by zolkis** [w3c/permissions#47]
In order to integrate the Permissions API with the [Web NFC API](http://w3c.github.io/web-nfc/index.html) spec, could you please include a new `"nfc"` entry to the permission name list.

**Comment by jyasskin** [comment]
Now that we've finally figured out how other specs should define permissions, could you add a `<dfn data-dfn-for="PermissionName" data-dfn-type="enum-value" data-export id="dom-permissionname-nfc">"nfc"</dfn>` to http://w3c.github.io/web-nfc/index.html with a description of how the [Permission Registry algorithms and types](https://w3c.github.io/permissions/#permission-registry) should be defined? Once that's done, ping here, and we'll add "nfc" to the enum definition.

**Comment by marcoscaceres** [comment]
Closing, as it's actually our spec that defines the "nfc" enum.
