### ISSUE TITLE
Is `Permissions.get` the right name?

### ISSUE THREAD

**Issue by jyasskin** [w3c/permissions#5]
`Permissions.get('geolocation')` looks to me like it's going to request the geolocation permission—that is, request access to the user's location.

Maybe `Permissions.check` or `Permissions.has` would be more self-descriptive?

**Comment by marcoscaceres** [comment]
`check` seems nice.

**Comment by mvano** [comment]
I agree with Marcos on `check` as `has` would imply a boolean value.

**Comment by mounirlamouri** [comment]
Just realised today that I wasn't watching this repository so I missed that issue. (Somehow my brain thought I would get notification because I created it.)

We decided months age to move from ```.get()``` to ```.query()```.
Would you guys prefer ```.check()``` over ```.query```?

**Comment by jyasskin** [comment]
`.query()` is fine with me.

**Comment by mvano** [comment]
Sure, `query` works for me.

**Comment by mounirlamouri** [comment]
FWIW, the spec has been updated to ```.query()```.

**Comment by mounirlamouri** [comment]
Closing per above comment.
