### ISSUE TITLE
This could replace the Quota Management API?

### ISSUE THREAD

**Issue by jimmywarting** [w3c/permissions#51]
I'm thinking in style of:

```
var bytes = 20*1024*1024; /* 20 MB */
navigator.permissions.request({name: "persistent", quota: bytes})
```

> The plan is to put all HTML5 offline storage APIs—including IndexedDB, Application Cache, File System,{# LocalStorage, SessionStorage,#} and other APIs that might be specified—under the Quota Management API. You will be able to manage all storage allocation with it.
> ref: https://developer.chrome.com/apps/offline_storage#future

[Quota Management API](http://www.w3.org/TR/quota-api/)

**Comment by marcoscaceres** [comment]
closing as out of scope.
