### ISSUE TITLE
Options for "double-keying" permissions

### ISSUE THREAD

**Issue by martinthomson** [w3c/permissions#55]
The Media Capture Task Force is currently discussing the possibility of keying permissions for `getUserMedia` on the combination of the origin of the requesting browsing context as well as the origin of the top-level browsing context.  That is, what you see in the location bar plus the actual requesting origin.  The permissions API doesn't permit additional levels of control like this currently.

I'll note that there are other browsers that key certain permissions on the same tuple of two origins.

**Comment by alvestrand** [comment]
The permissions API is rather unclear about whether it supports two-level keying or not.

**Comment by martinthomson** [comment]
Actually, I think that this might not be a problem. [This](https://w3c.github.io/permissions/#dfn-permission-storage-identifier) says:

> The permission storage identifier MUST contain the website's origin and MAY contain other information like the embedding status or the embedder's origin.

**Comment by alvestrand** [comment]
This is a problem if any implementors choose to not do the MAY - so I'd be happier if it said "MUST include the embedding status and the embedder's origin".

**Comment by martinthomson** [comment]
Yes, I agree that this is a problem in the sense that it makes writing code to the API (all of them) quite difficult.

I expect that site authors will want a single, broad key in the same way that the privacy-/security-conscious will want the narrower double-key.  We should probably ensure that there is a wider discussion.

**Comment by mounirlamouri** [comment]
I don't think we are in a situation where we can realistically tell UA the exact rules regarding permission handling. Every browser have their own way to deal with permissions. All use the requesting origins. Some like Chromium based browsers might use the embedder's origin. For example, Chrome uses the embedder's origin for the geolocation API while last I checked Firefox doesn't. However, at the time of writing, Chrome doesn't use the embedder's origin for Notifications permission, so does Firefox.

Even if all browsers had the same behaviour, browsers might want to evolve their permission handling. For example, Chrome and Firefox are slowly deprecating some APIs on insecure origins. A direct consequence would be that the API will be exposed as denied regardless of the origin if it isn't considered secure. We can imagine that a browser might stop allowing embedded origins to access some API.

What the Permissions API does is exposing whether the website has access to the API in the current context. The browser implementation of the Permissions API should take into account whether the embedder's origin is used in that decision. This said, I'm not sure how and why the website should be aware of this.

**Comment by martinthomson** [comment]
I think that there is little point in doing this whole standardization thing unless we tackle the hard problems as well as the easy ones.

The problem that most concerns me here is that the key for permissions constrains applications in the way they deploy.  If a popular browser does not key on the embedding origin, then provisions in the application for requesting permissions will be less able to handle being embedded in a browser the does key on the embedding origin.

I don't decide this for Firefox, but I'd venture that we'd be willing to make changes to how permissions are keyed if that means that application developers and users get a more consistent experience.  Maybe it's a decision we need to make on a per-API basis, but there aren't that many to work through. (My intuition is that the right answer is double-keys for all except notifications.)

The changes to availability of features on insecure origins shouldn't have any impact on this.  The intent there is to present consistent behaviour between browsers in the same way that I'm suggesting here.

**Comment by mounirlamouri** [comment]
My problem isn't whether it's a hard problem to tackle but whether it's a problem that should be tackled. Telling UA to do something while we know they are not doing it and they might stop doing it doesn't sound like a good idea. Browsers don't agree with each other (as far as their actual behaviour is concerned) and even different permissions for the same browsers behave differently. People at Google are actually looking into how Chrome handles iframe permissions.

Maybe another way to put my concern is that we should look into specifying the behaviour if browsers agree on a common behaviour and agree to stick to a common behaviour. Not force the behaviour upon browsers from the spec.

**Comment by alvestrand** [comment]
If Chrome implementors and Firefox implementors together are saying that they think double keying (perhaps per permissions group, perhaps for all permissions) is a Good Idea, and that they percieve problems with the spec not mandating double keying, I think that's a hint that the browser vendors might stick to the common behavior if specified.
I'm trying to see an argument in favor of the "implementations are free to vary" language, and not finding any at the moment.

**Comment by mounirlamouri** [comment]
To focus the discussion on the Permissions API, I think the API should mention that the rules regarding permissions should match the original spec if any. I don't think it's a good idea to have a general rule at this point. Some browsers (like Chrome) don't even have consistent rules between permissions. I'm open to the idea of having generic permission model for the web that is browser compatible but that's not something I'm particularly interested to invest time on because browsers have way too many reasons to behave one way or another (UI, privacy and security considerations).

For specific permissions, if a specification want to specify rules, I guess it's up to them to decide. Some for example, deny permissions for insecure origins.

**Comment by alvestrand** [comment]
Are you saying that it makes sense for the permissions spec to say "WebRTC permissions are double-keyed"?
That would certainly make behavior more consistent for the properties I care about.

**Comment by mounirlamouri** [comment]
I think it makes sense for the permissions spec to say "if WebRTC spec as specific requirements, do as they say, otherwise, you it is RECOMMENDED to do something along these lines [...]".

**Comment by martinthomson** [comment]
I can live with that conclusion.  Expect further contact regarding permissions models for various APIs.  It would be good to have that consistent.

**Comment by mounirlamouri** [comment]
Closing this given that we decided to leave double keying outside of browser requirements at the moment.
