### ISSUE TITLE
Could we ask for several permissions at a time ?

### ISSUE THREAD

**Issue by QuentinFchx** [w3c/permissions#6]
What if I want to ask 2 or more permissions at the same time ?
`Permissions.get(['geolocation', 'fullscreen'])` would be nice.

**Comment by mounirlamouri** [comment]
We could but what would be the benefit over:
```Promises.all([Permissions.get('geolocation'), Permissions.get('fullscreen')]);```

Slightly less characters for sure but make good usage of current tools the platform provides.

**Comment by marcoscaceres** [comment]
What @mounirlamouri said, the simpler API is much more composable.

**Comment by mounirlamouri** [comment]
Let's close this if we agree :)

**Comment by QuentinFchx** [comment]
From a browser/UI perspective, I guess it would allow to display a custom UI element asking for several permissions at a time.

"À la Facebook"
![](https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-ash2/t39.2178-6/10333109_1431654790418445_296535717_n.png)

**Comment by mounirlamouri** [comment]
```Permissions.query()``` is to check whether you have permissions. This specification does not provide a way to request permissions. Unfortunately, your use cases can't be achieved with the current tools.

**Comment by QuentinFchx** [comment]
Alright, I confused `.query` and a sort of `.request`.
As you mentionned in https://github.com/w3c/permissions/issues/4#issuecomment-77388068, why isn't `.request` a part of this spec ?

**Comment by marcoscaceres** [comment]
On March 6, 2015 at 2:33:51 AM, Quentin (notifications@github.com) wrote:
> Alright, I confused `.query` and a sort of `.request`.
> As you mentionned in https://github.com/w3c/permissions/issues/4#issuecomment-77388068,  
> why isn't `.request` a part of this spec ?

There are strong opinions about `.request()` ... including IPR concerns, IIRC. We are still trying to see if it can be included.

**Comment by RichardMaher** [comment]
Agree very much with @QuentinFchx ! User faticue at a series of pop-up permission questions will be fatiguing. Several permissions will allways have to be requested as a batch at App Start

**Comment by marcoscaceres** [comment]
Why? The right way to do it is this way: https://techcrunch.com/2014/04/04/the-right-way-to-ask-users-for-ios-permissions/

It an app is asking for permissions in some other way, it's just doing it wrong - but that's not the platform's fault. The app developer just needs to do a better job at providing a good experience.

**Comment by RichardMaher** [comment]
The jury is in and the recommendations in that article and elsewhere are correct and help deliver the user-experience we all aspire to.  As @QuentinFchx implies, perhaps you should lecture Facebook.

Having said that, there is nothing that rules out adhering to those guidelines yet needing to ask for more than one permission simultaneously. For example, my NoteToSelf App is going to want to use the Camera and the Microphone. Do we a) annoy the user twice in rapid succession for a potential string or permissions or b) Explain why the posterity-recording function needs sight and sound?

How about GeoLocation and Notifications if it's a geofence traversal Usurper Web App. "Hey crazy user Bargain Hunter needs your location to work out which one of our partners your next to and Notifications to let you know when there's a red-hot bargain on!
Do you consent to Bargain Hunter to access you Location and send you Notifications?"

No brainer!

Or if we decide to tackle the granularity is: - "Usurper needs to access your location to send the ambulance. Do you agree to Usurper: -
[tickbox] Accessing your location while you are viewing the App
[tickbox] Accessing your location while your device is asleep or on a different App
[tickbox] Using accurate GPS readings that may use battery power more quickly

**Comment by marcoscaceres** [comment]
> Having said that, there is nothing that rules out adhering to those guidelines yet needing to ask for more than one permission simultaneously.

There is tho: The web platform doesn't really allow that right now. Google did some experimentation with grouping permissions if asked in the same turn of the even loop - I don't know if those experiments went anywhere tho and they just reverted back. 

Representation of multiple requests at once are not accepted practice across browsers. In fact, the whole `.request()` method is so contentious, that Mozilla has repeatedly asked for it to be removed from the spec entirely: https://github.com/w3c/permissions/issues/83
