### ISSUE TITLE
Add 'background-sync' permission

### ISSUE THREAD

**Issue by nicolassatragno** [w3c/permissions#60]
Users should be able to disable [background sync](https://wicg.github.io/BackgroundSync/spec/). There is already [discussion](https://github.com/WICG/BackgroundSync/issues/122) going on about what to do if permission is blocked. In the meantime, it is desirable to expose this information on the Permissions API.

I suggest adding a `background-sync` element to PermissionName. I am happy to provide a PR with the change.

What do you think?

**Comment by mounirlamouri** [comment]
@jkarlin and @mkruisselbrink, I can't find any mention of permission in the spec and the linked issue isn't resolved. Are you moving to a permission-based API?

**Comment by mkruisselbrink** [comment]
> Are you moving to a permission-based API?

At least in chrome we're likely never going to prompt for a background sync permission, but yes, we are going to add the possibility for users to disable background sync. We just haven't gotten around to updating the spec to address this possibility.
(as an aside, it doesn't seem very maintainable long term if every feature with a permission will need to update the permissions API spec... having such circular dependencies between feature and permissions API seems like it would make it impossible to move any spec forward as you don't want a "more stable" spec to depend on a "less stable" spec. Why can't specs just define their extensions to the permissions API in their own spec text?)

**Comment by beverloo** [comment]
+1 to the extensions question, we'd also like to do this with push and possibly notifications.

**Comment by marcoscaceres** [comment]
About extensions, it's fine for specs to do that in their own specs as a monkey patch - but as a community, we should make the effort to come back to this spec once the new permission is adopted (just file a bug).
