### ISSUE TITLE
Need information about whether a permission is persistent or temporary

### ISSUE THREAD

**Issue by alvestrand** [w3c/permissions#63]
In one case (closing a device), the getusermedia spec says that it will revoke a permission if the permission granted is temporary, while it will not revoke it if it's permanent. This distinction is presently not present in the permissions spec.

Suggestion: Add to the PermissionStatus interface a boolean flag:

  boolean transient = false;

with the description

if "transient" is false, the permission is granted on an ongoing basis.
If "transient" is true, the permission is based on being used at present, and is expected to be deleted (which will revert it to its default state) as soon as it is no longer being used.

The lifetime of an ongoing permission is browser dependent. For permissions granted on insecure origins [[ref]], the lifetime MUST NOT (????) be longer than the lifetime of the top level browsing context.

**Comment by KOLANICH** [comment]
:-1:

**Comment by alvestrand** [comment]
On re-evaluating, "transient" permissions are better handled inside getusermedia. Closing request.
