### ISSUE TITLE
Add terms to Shepherd

### ISSUE THREAD

**Issue by jyasskin** [w3c/permissions#64]
I'm trying to integrate the Permissions API into the Web Bluetooth spec, but the Permissions spec doesn't export enough definitions for Bikeshed to auto-link properly. In the first four paragraphs, I've needed [`PermissionDescriptor`](https://w3c.github.io/permissions/#idl-def-PermissionDescriptor) and [associated PermissionDescriptor](https://w3c.github.io/permissions/#dfn-associated-permissiondescriptor), but please also export anything else a spec would need in order to define a new permission.

@tabatkins will know what you need to change to get the definitions imported. https://github.com/tabatkins/bikeshed/blob/master/docs/dfn-contract.md says what the final HTML needs to be, but I don't know the ReSpec source to generate that.

**Comment by marcoscaceres** [comment]
I think this was resolved with the move to BS.

**Comment by marcoscaceres** [comment]
@jyasskin, please reopen if that is not correct.
