### ISSUE TITLE
Changing FATAL/WARNING signalling a little bit

### ISSUE THREAD

**Issue by tabatkins** [w3c/permissions#65]
Right now all the errors that stop normal spec generation are marked as "FATAL ERROR". This looks really scary if you're first converting a spec, even though most errors are linking errors.  Also, not to denigrate linking errors (they definitely need to be fixed), but they clutter up the output and make it harder to find the *big* errors that might actually screw something up in the spec.

Plan
------
* [ ] Switch all the linking errors to say "LINKING ERROR" instead, outputting in a different color. That way the red errors *really* stand out.  (Maybe switch linking errors to yellow, and move WARNINGs to some other color?)
* [ ] Don't make linking errors fatal. Specs should still generate with linking errors.
* [ ] Output a status message at the end in some cases.  Thinking of "Success, but with X linking errors", "Failure due to fatal errors", and "Success, but fatal errors were suppressed".  No message when things work correctly, as today.

Anyone see anything crazy about this that would super bug them?  @annevk @domenic @dbaron @jyasskin

**Comment by jyasskin** [comment]
This is probably on the wrong repository. Otherwise, sounds like a good plan.

**Comment by tabatkins** [comment]
...fuck me
