### ISSUE TITLE
Add pointerlock to the permissions enum? 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/permissions#67]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1252749#c2

**Comment by mounirlamouri** [comment]
Isn't pointer lock like fullscreen a feature that is moving to be always allowed?

**Comment by marcoscaceres** [comment]
Dunno. I haven't heard anything about that.

**Comment by jyasskin** [comment]
Per #103, we're trying to put new PermissionName enum value definitions in their own specs. So, if pointerlock wants an entry in the permissions enum, it should add a definition, and ping this bug, and then we'll add the entry to the enum definition.

@scheib FYI.

**Comment by raymeskhoury** [comment]
I'm not opposed to adding permissions to the API for these, but in Chrome we don't have these behind prompts.

**Comment by annevk** [comment]
Firefox is removing the prompt. Only Edge still has a prompt, but I suppose they'll align too.

**Comment by annevk** [comment]
Given that I don't think we should add permissions for gesture-gated APIs since it doesn't mean much.

**Comment by marcoscaceres** [comment]
closing, as per https://github.com/w3c/permissions/issues/67#issuecomment-235818464 (pointerlock is always on)
