### ISSUE TITLE
What should "retrieve the permission state" do for pickers? 

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/permissions#8]
We need use cases for that in order to start extending the algorithm to include it. My first thoughts would be that pickers and permissions are opposed: if you have a picker, you probably have no associated permission.

If I had to make a pure theoretical exercise and try to have pickers fit in the current model, I think it should be something like `granted` the reason being that `prompt` will send the wrong signal to the web page, making it think the permission can be `granted` by the user.

This said, the only picker commonly used on the web is for `<input type=file>` and having a permission associated with that doesn't sound right.

**Comment by martinthomson** [comment]
The only picker commonly used on the web is what exactly?

Firefox has pickers for getUserMedia, at least if I correctly understand what you mean by picker.

**Comment by jonathanKingston** [comment]
Perhaps in the implementation for getUserMedia it should actually be two permissions for video and audio. The specification doesn't list how the user agent should ask for permissions (that could be a nice addition later to define how permissions are approved).

**Comment by marcoscaceres** [comment]
@mounirlamouri, Is this handled by PermissionDescription (and any extensions made by relevant specifications)?

**Comment by marcoscaceres** [comment]
closing, as this no longer seems relevant.
