### ISSUE TITLE
Why is "retrieve the permission storage" not in "Permission store"?

### ISSUE THREAD

**Issue by g-ortuno** [w3c/permissions#84]
Why is [retrieve the permission storage](https://w3c.github.io/permissions/#retrieve-the-permission-storage) not in [Permission store](https://w3c.github.io/permissions/#permission-store)?

I think moving it to [Permission store](https://w3c.github.io/permissions/#permission-store) would make is easier to see PermissionStorage's algorithms.

**Comment by jyasskin** [comment]
https://rawgit.com/jyasskin/permissions/update-permission/index.html#storage-manipulation does this move. See what you think.

**Comment by jyasskin** [comment]
Fixed by #97.
