### ISSUE TITLE
Switch to having TravisCI build the spec

### ISSUE THREAD

**Issue by jyasskin** [w3c/permissions#89]
Discussed in https://github.com/w3c/permissions/pull/87#issuecomment-213247119.

@domenic has a script for this in https://github.com/w3ctag/promises-guide/blob/master/deploy-gh-pages.sh.

**Comment by mounirlamouri** [comment]
Sound fun, will have a look tonight.

**Comment by mounirlamouri** [comment]
/CC @marcoscaceres FYI

This is done. We should now use `master` and travis will automatically build index.html and commit the change to gh-pages.

Please notice that `master` is the new default branch instead of `gh-pages`.

**Comment by jyasskin** [comment]
Thanks!
