### ISSUE TITLE
Separate "request access" from "request permission"?

### ISSUE THREAD

**Issue by alvestrand** [w3c/permissions#94]
As detailed in https://github.com/w3c/mediacapture-main/issues/350 the term "request permission" is ambigous; it may be interpreted either as a request for access to the underlying resource or as a request for a permission entry to be created and stored.

Suggestion: Call the "request a permission" algorithm "request access", and let the creation of a permission entry be an optional feature (as indicated in #93 )

**Comment by jyasskin** [comment]
I think this was resolved by #97. Please reopen if we still need changes for this.
