### ISSUE TITLE
how to tidy?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/permissions#98]
As part of the move to bs, we agreed that we would do the move if we could tidy the document. 

@jyasskin, I've got a bunch of editorial changes I'd like to make, but I can't seem to tidy the doc (it ends up a with a big mess). 

Any suggestions?

**Comment by jyasskin** [comment]
See https://github.com/tabatkins/bikeshed/issues/662#issuecomment-208403210. What kinds of mess is tidy introducing that I missed in that comment?

@tabatkins

**Comment by marcoscaceres** [comment]
Yes, I saw that. But I'm wondering how you had handled this problem when you transitioned this document to bs (if you bothered at all with it). 

Right now, I'm just having to paste bits of markup into http://jsbeautifier.org/ 
(which, as you can imagine, gets pretty old pretty quick)

Maybe I need to stop worrying and learn to love soft wrapping :)

**Comment by jyasskin** [comment]
I think I didn't handle it when converting to bikeshed: I wanted to keep the diff as clean as possible, which meant no rewrapping.

**Comment by marcoscaceres** [comment]
Ok, thanks for the clarification. Will keep doing it manually.
